apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world-service
spec:
  type: NodePort
  selector:
    app: flask-hello-world
  ports:
    - protocol: TCP
      port: 5000         # Service port
      targetPort: 5000   # Flask app port
      nodePort: 30007    # External access port (30000-32767)
